export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE"


export const HOME_VIDEO_SUCCESS = "HOME_VIDEO_SUCCESS";
export const HOME_VIDEO_FAIL = "HOME_VIDEO_FAIL";
export const HOME_VIDEO_START = "HOME_VIDEO_START"


export const VIDEO_DETAILS_SUCCESS = "VIDEO_DETAILS_SUCCESS";
export const VIDEO_DETAILS_FAIL = "VIDEO_DETAILS_FAIL";
export const VIDEO_DETAILS_START = "VIDEO_DETAILS_START"

export const RELATED_VIDEO_DETAILS_SUCCESS = "RELATED_VIDEO_DETAILS_SUCCESS";
export const RELATED_VIDEO_DETAILS_FAIL = "RELATED_VIDEO_DETAILS_FAIL";
export const RELATED_VIDEO_DETAILS_START = "RELATED_VIDEO_DETAILS_START"

export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";
export const CHANNEL_DETAILS_START = "CHANNEL_DETAILS_START"


export const SUBCRIPTION_DETAILS_SUCCESS = "SUBCRIPTION_DETAILS_SUCCESS";

export const COMMENT_DETAILS_START = "COMMENT_DETAILS_START";
export const COMMENT_DETAILS_SUCCESS = "COMMENT_DETAILS_SUCCESS";
export const COMMENT_DETAILS_FAIL = "COMMENT_DETAILS_FAIL";

export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_FAIL = "COMMENT_ADD_FAIL";

export const SUBSCRIPTION_DETAILS_SUCCESS = "SUBSCRIPTION_DETAILS_SUCCESS";
export const SUBSCRIPTION_DETAILS_FAIL = "SUBSCRIPTION_DETAILS_FAIL";
export const SUBSCRIPTION_DETAILS_START = "SUBSCRIPTION_DETAILS_START"